# Generated by Django 4.1.7 on 2023-03-15 11:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bikes',
            fields=[
                ('bike_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_company', models.CharField(max_length=50)),
                ('bike_model', models.CharField(max_length=100)),
                ('bike_cost', models.IntegerField()),
                ('bike_availability', models.IntegerField(default=1)),
                ('bike_colour', models.CharField(max_length=30)),
                ('bike_millage', models.IntegerField()),
                ('bike_cc', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='bike images')),
            ],
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_city', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('take_time', models.DateTimeField(default=datetime.datetime(2023, 3, 15, 15, 59, 46, 249010))),
                ('give_time', models.DateTimeField(default=datetime.datetime(2023, 3, 15, 15, 59, 46, 249010))),
                ('cost', models.IntegerField(default=0)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentaBike.bikes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bikes',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentaBike.branches'),
        ),
    ]
