CREATE TABLE customer_review (
  review_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  film_id INT NOT NULL,
  language_id INT NOT NULL,
  title VARCHAR(255),
  score INT,
  review_text TEXT,
  last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (film_id) REFERENCES new_film(id) ON DELETE CASCADE)



